# Metadata:
#   File: internal/cmd/migrate.go
#   Covers: migrate command

Feature: Migrate documentation for a Terraform provider
  In order to use the new template-based documentation system
  As a provider developer
  I want to use the `tfplugindocs migrate` command

  Scenario: Migrating from legacy directory structure
    Given a Terraform provider with the following legacy documentation:
      | File                                | Content                                                                                               |
      | website/docs/r/test_resource.html.markdown | ---
page_title: "test_resource"
---
# test_resource
## Example Usage
```hcl
resource "test_resource" "example" {}
```
 |
      | website/docs/d/test_data_source.html.markdown | ---
page_title: "test_data_source"
---
# test_data_source
## Example Usage
```hcl
data "test_data_source" "example" {}
```
 |
    When I run `tfplugindocs migrate`
    Then the following files should be generated:
      | File                                      | Content                                                                                                                                                             |
      | templates/resources/test_resource.md.tmpl   | ---
page_title: "test_resource"
---
<!--
This file is automatically generated.
Please refrain from modifying this file directly.
Instead, locate the corresponding template in the templates directory and make your changes there.
-->
# test_resource
## Example Usage
{{tffile "examples/resources/test_resource/example_1.tf"}}
 |
      | templates/data-sources/test_data_source.md.tmpl | ---
page_title: "test_data_source"
---
<!--
This file is automatically generated.
Please refrain from modifying this file directly.
Instead, locate the corresponding template in the templates directory and make your changes there.
-->
# test_data_source
## Example Usage
{{tffile "examples/data-sources/test_data_source/example_1.tf"}}
 |
      | examples/resources/test_resource/example_1.tf      | resource "test_resource" "example" {}                                                                                                                       |
      | examples/data-sources/test_data_source/example_1.tf  | data "test_data_source" "example" {}                                                                                                                        |
    And the directory "website" should not exist

  Scenario: Migrating from docs directory structure
    Given a Terraform provider with the following documentation:
      | File                                      | Content                                                                                               |
      | docs/resources/test_resource.md           | ---
page_title: "test_resource"
---
# test_resource
## Example Usage
```hcl
resource "test_resource" "example" {}
```
 |
      | docs/data-sources/test_data_source.md     | ---
page_title: "test_data_source"
---
# test_data_source
## Example Usage
```hcl
data "test_data_source" "example" {}
```
 |
    When I run `tfplugindocs migrate`
    Then the following files should be generated:
      | File                                      | Content                                                                                                                                                             |
      | templates/resources/test_resource.md.tmpl   | ---
page_title: "test_resource"
---
<!--
This file is automatically generated.
Please refrain from modifying this file directly.
Instead, locate the corresponding template in the templates directory and make your changes there.
-->
# test_resource
## Example Usage
{{tffile "examples/resources/test_resource/example_1.tf"}}
 |
      | templates/data-sources/test_data_source.md.tmpl | ---
page_title: "test_data_source"
---
<!--
This file is automatically generated.
Please refrain from modifying this file directly.
Instead, locate the corresponding template in the templates directory and make your changes there.
-->
# test_data_source
## Example Usage
{{tffile "examples/data-sources/test_data_source/example_1.tf"}}
 |
      | examples/resources/test_resource/example_1.tf      | resource "test_resource" "example" {}                                                                                                                       |
      | examples/data-sources/test_data_source/example_1.tf  | data "test_data_source" "example" {}                                                                                                                        |
    And the directory "docs" should not exist
